# Generated by Django 3.2.4 on 2021-06-29 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Console', '0001_initial'),
        ('SharedApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedownloadobjectstat',
            name='indexObject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.indexobject'),
        ),
        migrations.AddField(
            model_name='filedownloadinstance',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.indexobject'),
        ),
        migrations.AddField(
            model_name='filedownloadinstance',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SharedApp.project'),
        ),
        migrations.AddField(
            model_name='filedownloadinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
