# Generated by Django 3.2.4 on 2021-06-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Console', '0005_alter_filedownloadinstance_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedownloadinstance',
            name='stat',
        ),
    ]
