# Generated by Django 3.2.4 on 2021-07-02 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StorageSettings',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SharedApp.project')),
                ('allowUserRead', models.BooleanField(default=True)),
                ('allowUserWrite', models.BooleanField(default=True)),
                ('allowAccessControl', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.developer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='Notification Text')),
                ('read', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=25)),
                ('enabled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('integrationKey', models.CharField(max_length=64)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.platform')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='IndexObject',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('objectType', models.CharField(choices=[('FD', 'folder'), ('FL', 'file')], default='FL', max_length=6)),
                ('name', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now=True)),
                ('size', models.IntegerField(default=0)),
                ('fileReference', models.TextField()),
                ('fileType', models.CharField(max_length=25)),
                ('allowAllUsersWrite', models.BooleanField(default=False)),
                ('allowAllUsersRead', models.BooleanField(default=False)),
                ('allowKeyUsersRead', models.BooleanField(default=True)),
                ('allowKeyUsersWrite', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SharedApp.indexobject')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='FileKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateObtained', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.indexobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField()),
                ('accessed', models.DateTimeField(auto_now=True)),
                ('accessedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.TextField(default=None)),
                ('integration', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='SharedApp.integration')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeletedIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.integration')),
            ],
        ),
        migrations.CreateModel(
            name='deletedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='None')),
                ('deletedBy', models.TextField(default='None')),
                ('owner', models.TextField(default='None')),
                ('fileID', models.TextField(default='None')),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SharedApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='BarnedDeveloperClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.developerclient')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.project')),
            ],
        ),
    ]
