# Generated by Django 3.2.4 on 2021-07-02 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SharedApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerclient',
            name='integration',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SharedApp.integration'),
        ),
    ]
