# Generated by Django 3.1.7 on 2021-06-01 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SharedApp', '0003_developerclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarnedDeveloperClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.developerclient')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.project')),
            ],
        ),
    ]
