# Generated by Django 3.2.4 on 2021-07-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedApp', '0003_alter_developerclient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerclient',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
