# Generated by Django 3.2.4 on 2021-07-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedApp', '0006_alter_barneddeveloperclient_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcollaboration',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
