# Generated by Django 3.1.7 on 2021-06-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SharedApp', '0007_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.integration')),
            ],
        ),
    ]
