# Generated by Django 3.2.4 on 2021-07-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedApp', '0008_auto_20210711_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='stored',
            field=models.IntegerField(default=0),
        ),
    ]
