# Generated by Django 3.1.7 on 2021-06-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedApp', '0010_downloadstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='deletedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField()),
                ('deleted', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
