# Generated by Django 3.2.4 on 2021-07-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SharedApp', '0010_integration_devices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='identification',
        ),
    ]
