# Generated by Django 3.2.4 on 2021-07-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SharedApp', '0011_rename_name_project_identification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='identification',
            new_name='name',
        ),
    ]
