# Generated by Django 3.2.4 on 2021-07-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SharedApp', '0012_rename_identification_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexobject',
            name='root',
            field=models.BooleanField(default=False),
        ),
    ]
