# Generated by Django 3.1.7 on 2021-06-02 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SharedApp', '0013_auto_20210601_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCollaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.developer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.project')),
            ],
        ),
    ]
