# Generated by Django 3.1.7 on 2021-06-06 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SharedApp', '0014_teamcollaboration'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexObject',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('objectType', models.CharField(choices=[('FD', 'folder'), ('FL', 'file')], default='FL', max_length=6)),
                ('name', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now=True)),
                ('size', models.IntegerField(default=0)),
                ('fileReference', models.TextField()),
                ('fileType', models.CharField(max_length=25)),
                ('allowAllUsersWrite', models.BooleanField(default=False)),
                ('allowAllUsersRead', models.BooleanField(default=False)),
                ('allowKeyUsersRead', models.BooleanField(default=True)),
                ('allowKeyUsersWrite', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SharedApp.indexobject')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.project')),
            ],
        ),
    ]
