# Generated by Django 3.1.7 on 2021-06-12 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SharedApp', '0015_indexobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filekey',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SharedApp.indexobject'),
        ),
    ]
