# Generated by Django 3.1.7 on 2021-06-01 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancedSubscription',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('expiryDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UnverifiedUser',
            fields=[
                ('username', models.TextField()),
                ('email', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('verificationCode', models.CharField(default='000000', max_length=6)),
                ('verificationLink', models.CharField(default='not set', max_length=128)),
                ('expiry', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('slug', models.CharField(default='xxEO1', max_length=128)),
                ('attempts', models.IntegerField(default=3)),
                ('expiry', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
