# Generated by Django 3.1.7 on 2021-05-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnverifiedUser',
            fields=[
                ('username', models.TextField()),
                ('email', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
            ],
        ),
    ]
