# Generated by Django 3.1.7 on 2021-05-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0002_unverifieduser_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unverifieduser',
            name='code',
        ),
        migrations.AddField(
            model_name='unverifieduser',
            name='verificationLink',
            field=models.CharField(default='not generated', max_length=128),
        ),
    ]
