# Generated by Django 3.1.7 on 2021-05-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0004_dummy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dummy',
        ),
        migrations.RemoveField(
            model_name='unverifieduser',
            name='verificationLink',
        ),
        migrations.AddField(
            model_name='unverifieduser',
            name='verificationCode',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
