# Generated by Django 3.1.7 on 2021-05-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0005_auto_20210520_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifieduser',
            name='verificationLink',
            field=models.CharField(default='not set', max_length=128),
        ),
    ]
