# Generated by Django 3.1.7 on 2021-05-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0007_recoveryobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryobject',
            name='slug',
            field=models.CharField(default='xxEO1', max_length=128),
        ),
    ]
