# Generated by Django 3.1.7 on 2021-05-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0008_recoveryobject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryobject',
            name='attempts',
            field=models.IntegerField(default=3),
        ),
    ]
