# Generated by Django 3.1.7 on 2021-05-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0010_recoveryobject_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifieduser',
            name='expiry',
            field=models.DateTimeField(default='2020-01-01'),
        ),
        migrations.AlterField(
            model_name='recoveryobject',
            name='expiry',
            field=models.DateTimeField(),
        ),
    ]
