# Generated by Django 3.1.7 on 2021-05-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0011_auto_20210522_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverifieduser',
            name='expiry',
            field=models.DateTimeField(),
        ),
    ]
