# Generated by Django 3.1.7 on 2021-05-25 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('WebApplication', '0012_auto_20210522_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancedSubscription',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('expiryDate', models.DateTimeField()),
            ],
        ),
    ]
